import type { Metadata } from "next";
import "./globals.css";
import MenuBar from "@/components/MenuBar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="flex flex-col min-h-screen">
        <main className="flex-grow">{children}</main>
        <MenuBar />
      </body>
    </html>
  );
}
